-- CreateEnum
CREATE TYPE "Category" AS ENUM ('TECHNOLOGY', 'BUSINESS_AND_CAREER', 'DESIGN_AND_CREATIVITY', 'LIFESTYLE', 'HEALTH_AND_WELLNESS', 'EDUCATION_AND_LEARNING', 'OPINION_AND_STORIES', 'TRENDS_AND_CULTURE', 'OTHER');

-- AlterTable
ALTER TABLE "posts" ADD COLUMN     "category" "Category" NOT NULL DEFAULT 'OTHER';
